spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jongmin?currentSchema=redis-study?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&reWriteBatchedInserts=true
    username: postgres
    password: 1234

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: redis-study
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
